[credentials]
username = username
password = password

[settings]
# URL of the captive portal login page
portal_url = http://172.20.28.1:8002/index.php?zone=hostelzone

# A reliable URL to check for internet connectivity.
# It should return a 204 No Content status when successful.
connectivity_check_url = http://clients3.google.com/generate_204

retry_delay = 5
ssid = MBH2_WiFi